# 0. In linux do sudo su first (this is because of enviornment vars)
# 1. export APP_ENV=development
# 2. docker-compose build
# 3. docker-compose up -d

version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
      args:
        type_env: ${APP_ENV}
    stdin_open: true
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: dev-not-so-secret
      DATABASE_CONNECTION_NUMBER: 3
      DATABASE_DATABASE: app
      DATABASE_HOST: postgres
      DATABASE_IDLE_TIMEOUT_MILLISECONDS: 30000
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATABASE_USER: app
      PORT: 3033
    ports:
      - "3033:3033"
    volumes:
      - .:/node
    networks:
      - nodeapp-network
    entrypoint:
      - /bin/bash


  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres.dockerfile
    env_file:
      - ./docker/scripts/${APP_ENV}/environment.env
    ports:
      - "5432:5432"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
